#!/usr/bin/env node
// Reads the four .agents/skills/presentation-*/SKILL.md files and emits
// lib/generation/skills.generated.ts so the section-drafting and outline
// system prompts can embed them verbatim. Run via "predev" / "prebuild".

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const FILES = [
  { id: "OUTLINE", file: ".agents/skills/presentation-outline/SKILL.md" },
  { id: "CONTENT", file: ".agents/skills/presentation-content/SKILL.md" },
  { id: "DESIGN", file: ".agents/skills/presentation-design/SKILL.md" },
  { id: "NOTES", file: ".agents/skills/presentation-notes/SKILL.md" },
];

const OUT = path.join(ROOT, "lib/generation/skills.generated.ts");

function escape(content) {
  return content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const banner = "// AUTO-GENERATED by scripts/inline-skills.mjs. DO NOT EDIT.\n// Run `npm run inline-skills` (or `npm run dev` / `npm run build`) to refresh.\n\n";

const parts = [];
parts.push(banner);
for (const { id, file } of FILES) {
  const abs = path.join(ROOT, file);
  const raw = await fs.readFile(abs, "utf-8");
  parts.push(`export const SKILL_${id} = \`${escape(raw)}\`;\n\n`);
}

await fs.mkdir(path.dirname(OUT), { recursive: true });
await fs.writeFile(OUT, parts.join(""), "utf-8");
console.log(`[inline-skills] wrote ${path.relative(ROOT, OUT)} (${parts.join("").length} chars)`);
